### ISSUE TITLE
Conditional diffusion model doesn't sample all categories

### ISSUE THREAD

**Issue by jwuphysics** [fastai/fastdiffusion#4]
Thanks for adding this example @tcapelle! 

However, when I try running your notebook on Colab, I find that the `before_batch_sampling()` method doesn't seem to get called, or at least it doesn't appear to work as expected.

For example, after running the line 
```python
preds = ddpm_learner.get_preds()
```

I can check that `preds[1]` is a full batch of the same category, e.g. it looks like:
```python
TensorCategory([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                6, 6, 6, 6])
```

Have you encountered this bug?

**Comment by tcapelle** [comment]
Hey, this is pretty hacky code.
The `before_batch_sample` get's called when the `gather_preds` is added (on `learn.get_preds()`) and it actually does something ugly, and writes in `preds[0]` the outputs, on `preds[1]` you have the labels of the batch on the validation dataloader that is not being used!

**Comment by tcapelle** [comment]
Ping me on Discord if you want a walk-thru
